apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: sag-aplicacion-template
message:  Aplicacion creada en tu proyecto
metadata:
  annotations:
    openshift.io/display-name: ${APPLICATION_NAME}
    openshift.io/provider-display-name: ${APPLICATION_NAME}
    template.openshift.io/documentation-url: 
    template.openshift.io/long-description: SAG Template
  labels:
  name: sag-aplicacion-template
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      name: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1 
    selector:
      matchLabels:
        name: ${APPLICATION_NAME}
    template:
      metadata:
        labels:
          name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${APP_IMAGE}
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http-server
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPLICATION_NAME}
  labels:
    name: ${APPLICATION_NAME}
  spec:
    type: ClusterIP
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
    selector:
      name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      name: ${APPLICATION_NAME}
  spec:
    path: "/"
    to:
      kind: Service
      name: ${APPLICATION_NAME}
- apiVersion: autoscaling/v2 
  kind: HorizontalPodAutoscaler
  metadata:
    name: book-import
  spec:
    scaleTargetRef:
      kind: Deployment
      name: ${APPLICATION_NAME}
      apiVersion: apps/v1
    minReplicas: ${{MIN_REPLICAS}}
    maxReplicas: ${{MAX_REPLICAS}}
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: ${{CPU_TARGET_PERCENTAGE}}
parameters:
- description: The name for the application
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: book-import
- description: Repo URL for Image
  displayName: Image URL
  name: APP_IMAGE
  value: quay.io/jpacker/hugo-nginx:latest
  required: true
- name: MIN_REPLICAS
  description: 'HorizontalPodAutoscaler: min replicas'
  value: "1"
  required: true
- name: MAX_REPLICAS
  description: 'HorizontalPodAutoscaler: max replicas'
  value: "4"
  required: true
- name: CPU_TARGET_PERCENTAGE
  description: 'HorizontalPodAutoscaler: targetPercentage of cpuUtilization'
  value: '40'
  required: true
